services:
  server:
    image: ghcr.io/se2gruppe3/saboteur:latest

    restart: unless-stopped

    ports:
      - "53207:8080"

    env_file:
      - /home/grp-3/.env

    volumes:
      - saboteur_data:/data

volumes:
  saboteur_data: