sonar.projectName=saboteur-app

# 1. Sources and Tests configuration
sonar.sources=server/src/main/kotlin,shared/src/commonMain/kotlin
sonar.tests=server/src/test/kotlin

# 2. Binary configuration
sonar.java.binaries=app/app/build/tmp/kotlin-classes/debug

# 3. Coverage configuration
sonar.coverage.jacoco.xmlReportPaths=app/app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml

# 4. Coverage Exclusions
sonar.coverage.exclusions=app/app/src/main/java/**/*

# 5. Global Exclusions
sonar.exclusions=server/**/*

# 6. Encoding
sonar.sourceEncoding=UTF-8