sonar.organization=se2gruppe3
sonar.projectKey=SE2Gruppe3_saboteur_app
sonar.projectName=saboteur-app

# Source and Test roots
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=**/build/tmp/kotlin-classes/debug

# Report paths
sonar.junit.reportPaths=**/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=**/jacocoTestDebugUnitTestReport.xml

# DEACTIVATE COVERAGE FOR ALL NEW APP CODE
# This excludes the entire package from the 80% coverage requirement.
sonar.coverage.exclusions=app/src/main/java/com/aau/se2game/**/*, **/BuildConfig.java, **/R.java
