sonar.organization=se2gruppe3
sonar.projectKey=SE2Gruppe3_saboteur_app
sonar.projectName=saboteur-app

sonar.sources=app/app/src/main/java
sonar.tests=app/app/src/test/java
sonar.java.binaries=app/app/build/tmp/kotlin-classes/debug,app/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.junit.reportPaths=app/app/build/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=app/app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml

# Exclude UI, Activities, Navigation, and Theme files from coverage
# These are handled via UI tests or are simple boilerplate that doesn't require unit test coverage.
sonar.coverage.exclusions=**/activities/**,**/navigation/**,**/ui/theme/**,**/MainActivity.kt
