sonar.organization=se2gruppe3
sonar.projectKey=SE2Gruppe3_saboteur_app
sonar.projectName=saboteur-app

sonar.sources=app/src/main/java/com/aau/saboteur/viewModels
sonar.tests=app/src/test/java
sonar.java.binaries=app/build/tmp/kotlin-classes/debug,app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
